config/routes.rb
Rails.application.routes.draw do

  resources :courses
  resources :folders
  resources :assets

  devise_for :users
  # Define root URI
  devise_scope :user do
  	authenticated :user do
      #Naming the root routes causes mailboxer to crash when email is sent. Do not uncomment till fixed
    	root :to => 'pages#launchpad'#, as: :authenticated_root
  	end
  	unauthenticated :user do

    	root :to => 'devise/registrations#new'#, as: :unauthenticated_root
  	end
  end
  
  get '/courses/watch/:id' => 'courses#watch', as: :watch

  get '/courses/attend/:id'	=> "courses#attend", as: :attend
  # get "/courses/start_teaching/:id" => "courses#start_teaching", as: :start_teaching
  # get "/courses/start_learning/:id" => "courses#start_learning", as: :start_learning
  get "/courses/webcast/:id" => "courses#webcast", as: :start_teaching

  # Match routes for static pages
  get '/launchpad' => 'pages#launchpad'
  get '/add_push_session' => 'pages#add_push_session'
  get "/contacts/create_session/:id" => "contacts#create_session", as: :create_session
  post "/contacts/create_appointment/:id" => "contacts#create_appointment", as: :create_appointment


  post "/contacts/set_customer/:id" => "contacts#set_customer"
  get "/contacts/get_customer/:id" => "contacts#get_customer"
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "/contacts/mail_session/:id" => "contacts#mail_session", as: :mail_session
  get "/conversations/new_wrecp" => "conversations/new_wrecp", as: :conv_session
  post "/conversations/invite" => "conversations#invite", as: :invite
  #Route for webcast
  get '/webcast' => 'contacts#webcast'

  get '/assets' => 'assets#index'
  #This route is for file downloads 
  match "assets/get/:id" => "assets#get", :via => [:get], :as => "download"
  #To browse across folders
  match "browse/:folder_id" => "assets#browse",  :via => [:get], :as => "browse"
 
  #creating folders insiide another folder 
  match "browse/:folder_id/new_folder" => "folders#new", :via => [:get], :as => "new_sub_folder"

  #for uploading files to folders 
  match "browse/:folder_id/new_file" => "assets#new", :via => [:get], :as => "new_sub_file"
  #for renaming a folder 
  match "browse/:folder_id/rename" => "folders#edit", :via => [:get], :as => "rename_folder"

  #for sharing the folder 
  match "assets/share" => "assets#share", :via => [:post], :as => "share"

  resources :appointments, except: [:create, :edit, :show, :update, :destroy, :new]
  post '/appointments/make_payment/:id' => "appointments#make_payment", as: :make_payment

  # Resourceful routes for the contacts page
  resources :contacts , except: [:show, :destroy]do
    member do
      get :delete
    end  
  end  
  resources :conversations do
    resources :messages
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/conversations_controller.rb
require "#{Rails.root}/app/controllers/push_notifications"
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def new_wrecp

  end 
  def create
    recipients = User.where(id: conversation_params[:recipients])
    #Need to validate null subj and messages
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject],nil,conversation_params[:attachment]).conversation
   
    flash[:success] = "Your message was successfully sent!"
    recipients.each do |contact|
      notification = PushNotification.new("New message", "You have a new message from #{current_user.first_name} #{current_user.last_name}", mailbox_inbox_url, contact.id)
      notification.push()
    end
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end
   def invite
      UserMailer.email(current_user.first_name+" "+current_user.last_name, params[:invitee],params[:email]).deliver
      

  end
  private

  def conversation_params
    params.require(:conversation).permit(:attachment,:subject,:body,recipients:[])
  end

 
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <!--
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div> -->
  <div class="media-body panel">
    <h4 class="media-heading">
      <% if User.find(conversation.originator.id).role=="doctor" %>
        <b>From: </b><%= conversation.originator.first_name+" "+conversation.originator.last_name%>
      <% else %>
        <b>From: </b><%= conversation.originator.first_name+" "+conversation.originator.last_name%>
      <% end%> <br>
      <b>To:</b> <%=conversation.recipients.select{|r| r!=conversation.originator}.map{|r| r.first_name+" "+r.last_name }.join(", ") %><br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= link_to "View Message", conversation_path(conversation)  %> <br>
    <%= truncate conversation.messages.last.body, length: 145 %>
    
  </div>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { :multipart => true  } do |f| %>

  <div class="form-group">
    <%= f.label :recipients %>
    <% if current_user.role=='patient'%>
      <%= f.select(:recipients, current_user.contacts.map {|p| [ p.first_name+" "+p.last_name, p.id ] }, {}, { multiple: true , class: "js-example-basic-multiple form-control",id: "recipients",  :required => true })%>
    <%else%>
      <%= f.select(:recipients, User.all.collect {|p| [ p.first_name+" "+p.last_name, p.id ] }, {}, { multiple: true , class: "js-example-basic-multiple form-control",id: "recipients",  :required => true })%>
    <%end%>
  </div>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control",id:"subject",:required => true %>
  </div>
  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", id:"message",rows: 4,:required => true  %>
    
  </div>
  <div class="row">
    <div class="col-md-9 col-xs-12">
    <div class="input-group">
      <label class="input-group-btn">
        <span class="btn btn-primary btn-darkblue btn-file">
        Add attachment <%= f.file_field :attachment, style: "display: none;"%>  
        </span>
      </label>
      <input type="text" id="attachment-text" class="form-control" readonly="">
    </div> 
    <br>
    </div> 
    
    <div class="col-md-3 col-xs-12">
    <%= f.submit "Send Message", class: "btn btn-primary btn-darkblue" %>
    </div>
  </div>
<% end %>
<%= render partial: 'invite_form' %>

<script type="text/javascript">
var $exampleMulti = $(".js-example-basic-multiple").select2({tags: true});
$exampleMulti.select2('val', [<%= (params[:recp])? params[:recp]:"" %>]);
$(".js-example-basic-multiple").on('select2:select', function (e) { 
    //var selected_element = $(e.currentTarget);
    //var select_val = selected_element.val().pop();
    //console.log(parseInt(select_val),selected_element.val())

  new_val=$.grep($(".js-example-basic-multiple").select2('val'), function (value) {
    if (!(isNaN(parseInt(value)))){
      return true;
    }
    else{
      $("#invite_form").modal("show");
      return false;
    }
  });
  
  //$(".js-example-basic-multiple").select2('data', new_data);
  $exampleMulti.val(new_val).trigger("change")

    //if(isNaN(parseInt(select_val))){
     //   $('#invite_form').modal("show");
      //  $(".js-example-basic-multiple").select2('val',selected_element.val());
      //}

});
</script>

<script>
$(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
    console.log(numFiles);
    console.log(label);
    document.getElementById("attachment-text").value = label;
});
</script>

app/views/conversations/_index.html.erb

<div class="container contacts-container">
<div class="container"><h1> </h1></div>
<div id="exTab1">	
	<ul  class="nav nav-pills nav-justified panel">
			<li id = "b1a" class="active">
        	<a  href="#1a" data-toggle="tab"><b>Physicians</b></a>
			</li>

<!-- 			<% if current_user.role != "patient" %>
 -->				<li id = "b2a"><a href="#2a" data-toggle="tab"><b>Patients</b></a>
				</li>
			<!-- <% end %> -->

						
		
	</ul>

			<div class="tab-content clearfix">
			  <div class="tab-pane active" id="1a">
          			<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: messages_doctor } %>
				</div>
				<div class="tab-pane " id="2a">
          			<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: messages_patient } %>
				</div>
        		
			</div>
</div>
</span>
<script>

$(document).ready(function() {
	
	frag = window.location.search.split('frag=')[1]
	if (!frag == false) {
		$('#1a').removeClass('active');
  		$('#2a').removeClass('active');
  		$('#3a').removeClass('active');
  		$('#4a').removeClass('active');


  		$('#b1a').removeClass('active');
  		$('#b2a').removeClass('active');
  		$('#b3a').removeClass('active');
  		$('#b4a').removeClass('active');

  		$('#'+frag).addClass('active');
  		$('#b'+frag).addClass('active');

	}	

 


	$('.dtable').DataTable({
  	responsive: true,
  autoWidth: true
});

   $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
         .columns.adjust()
         .responsive.recalc();
   }); 	
});


</script>


app/views/conversations/_invite_form.html.erb

<div class="modal fade"
           id="invite_form" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="false" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title custom-blue"><i class=' glyphicon glyphicon-envelope custom-blue'></i>&nbsp;&nbsp;Contact hasn't signed up to Medimail</h3>
      </div>
    <div class="modal-body">Would you like to invite him/her to use this app?
      <br>
      <br>
      <%= form_tag :invite do %>

      <!-- <%= label_tag(:email, "Email") %> -->
      <%= email_field_tag :email, nil, class: 'form-control', placeholder: 'Email'%>
      <br>
      <!-- <%= label_tag(:invitee, "Name") %> --> 
      <%= text_field_tag  :invitee, nil,class: 'form-control', placeholder: 'Name' %>
      
    </div>
     <div class="modal-footer">
        <%= submit_tag  "Invite", class: "btn btn-primary" %>
        <% end %>
        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">

      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.first_name+" "+message.sender.last_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <div class="panel">
        <%= message.body %>

        <br>
        <br>
        <% if message.attachment? %>
          <strong>Attachment</strong>
          <%= link_to message.attachment.file.filename, message.attachment.url, target: :blank , :"download"=>message.attachment.file.filename%>
        <% end %>
        </div>      
      </div>
    </div>
<% end %>

app/views/conversations/email.text.erb
Sign up to Medimail, <%= @invitee %>!
===============================================
 
You have beem invited to join by <%= @user %>
 
To sign up to the site, just follow this link: <%= @url %>.
 
Have a great day!

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/new_wrecp.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <!--<%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>-->
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn', method: :post %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn  btn-primary btn-darkblue pull-right ' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>