config/routes.rb
Rails.application.routes.draw do

  resources :courses
  resources :folders
  resources :assets

  devise_for :users
  # Define root URI
  devise_scope :user do
  	authenticated :user do
      #Naming the root routes causes mailboxer to crash when email is sent. Do not uncomment till fixed
    	root :to => 'pages#launchpad'#, as: :authenticated_root
  	end
  	unauthenticated :user do

    	root :to => 'devise/registrations#new'#, as: :unauthenticated_root
  	end
  end
  
  get '/courses/watch/:id' => 'courses#watch', as: :watch

  get '/courses/attend/:id'	=> "courses#attend", as: :attend
  # get "/courses/start_teaching/:id" => "courses#start_teaching", as: :start_teaching
  # get "/courses/start_learning/:id" => "courses#start_learning", as: :start_learning
  get "/courses/webcast/:id" => "courses#webcast", as: :start_teaching

  # Match routes for static pages
  get '/launchpad' => 'pages#launchpad'
  get '/add_push_session' => 'pages#add_push_session'
  get "/contacts/create_session/:id" => "contacts#create_session", as: :create_session
  post "/contacts/create_appointment/:id" => "contacts#create_appointment", as: :create_appointment


  post "/contacts/set_customer/:id" => "contacts#set_customer"
  get "/contacts/get_customer/:id" => "contacts#get_customer"
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "/contacts/mail_session/:id" => "contacts#mail_session", as: :mail_session
  get "/conversations/new_wrecp" => "conversations/new_wrecp", as: :conv_session
  post "/conversations/invite" => "conversations#invite", as: :invite
  #Route for webcast
  get '/webcast' => 'contacts#webcast'

  get '/assets' => 'assets#index'
  #This route is for file downloads 
  match "assets/get/:id" => "assets#get", :via => [:get], :as => "download"
  #To browse across folders
  match "browse/:folder_id" => "assets#browse",  :via => [:get], :as => "browse"
 
  #creating folders insiide another folder 
  match "browse/:folder_id/new_folder" => "folders#new", :via => [:get], :as => "new_sub_folder"

  #for uploading files to folders 
  match "browse/:folder_id/new_file" => "assets#new", :via => [:get], :as => "new_sub_file"
  #for renaming a folder 
  match "browse/:folder_id/rename" => "folders#edit", :via => [:get], :as => "rename_folder"

  #for sharing the folder 
  match "assets/share" => "assets#share", :via => [:post], :as => "share"

  resources :appointments, except: [:create, :edit, :show, :update, :destroy, :new]
  post '/appointments/make_payment/:id' => "appointments#make_payment", as: :make_payment

  # Resourceful routes for the contacts page
  resources :contacts , except: [:show, :destroy]do
    member do
      get :delete
    end  
  end  
  resources :conversations do
    resources :messages
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox_doctor = mailbox.inbox.select { |conversation| User.find(conversation.originator.id).role=="doctor"}
    @inbox_patient = mailbox.inbox.select { |conversation| User.find(conversation.originator.id).role=="patient"}
    @active = :inbox
  end

  def sent
    @sent_doctor = mailbox.sentbox.select { |conversation| User.find(conversation.originator.id).role=="doctor"}
    @sent_patient = mailbox.sentbox.select { |conversation| User.find(conversation.originator.id).role=="patient"}
    @active = :sent
  end

  def trash
    @trash_doctor = mailbox.trash.select { |conversation| User.find(conversation.originator.id).role=="doctor"}
    @trash_patient = mailbox.trash.select { |conversation| User.find(conversation.originator.id).role=="patient"}
    @active = :trash
  end

end

app/helpers/mailbox_helper.rb
module MailboxHelper
  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).distinct.count(:id)
  end
end

app/views/mailbox/_folder_view.html.erb
<br>
<br>
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
   <!-- <%= link_to "Compose", new_conversation_path, class: "btn btn-primary btn-darkblue" %> -->
    <div class="spacer"></div>    
  </div>
  
  <div class="col-md-4">
    <br>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
        <br>
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'conversations/form' %>
        <% else %>
            <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/mailbox/_folders.html.erb

<ul class="nav nav-pills nav-stacked">

    <li class="<%= 'active' if params[:controller] == 'conversations' %>">
    <%= link_to new_conversation_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span id="Compose">Compose</span>
    <% end %>
  </li>

  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span id="Inbox">Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span id="Sent">Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span id="Trash">Trash</span>
    <% end %>
  </li>
</ul>

app/views/mailbox/inbox.html.erb
<%= render partial: 'conversations/index', locals: {messages_patient: @inbox_patient,messages_doctor: @inbox_doctor }%> <!--'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } -->

app/views/mailbox/sent.html.erb
<%= render partial: 'conversations/index', locals:  {messages_patient: @sent_patient,messages_doctor: @sent_doctor } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'conversations/index', locals:  {messages_patient: @trash_patient,messages_doctor: @trash_doctor } %>