config/routes.rb
Rails.application.routes.draw do

  resources :courses
  resources :folders
  resources :assets

  devise_for :users
  # Define root URI
  devise_scope :user do
  	authenticated :user do
      #Naming the root routes causes mailboxer to crash when email is sent. Do not uncomment till fixed
    	root :to => 'pages#launchpad'#, as: :authenticated_root
  	end
  	unauthenticated :user do

    	root :to => 'devise/registrations#new'#, as: :unauthenticated_root
  	end
  end
  
  get '/courses/watch/:id' => 'courses#watch', as: :watch

  get '/courses/attend/:id'	=> "courses#attend", as: :attend
  # get "/courses/start_teaching/:id" => "courses#start_teaching", as: :start_teaching
  # get "/courses/start_learning/:id" => "courses#start_learning", as: :start_learning
  get "/courses/webcast/:id" => "courses#webcast", as: :start_teaching

  # Match routes for static pages
  get '/launchpad' => 'pages#launchpad'
  get '/add_push_session' => 'pages#add_push_session'
  get "/contacts/create_session/:id" => "contacts#create_session", as: :create_session
  post "/contacts/create_appointment/:id" => "contacts#create_appointment", as: :create_appointment


  post "/contacts/set_customer/:id" => "contacts#set_customer"
  get "/contacts/get_customer/:id" => "contacts#get_customer"
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "/contacts/mail_session/:id" => "contacts#mail_session", as: :mail_session
  get "/conversations/new_wrecp" => "conversations/new_wrecp", as: :conv_session
  post "/conversations/invite" => "conversations#invite", as: :invite
  #Route for webcast
  get '/webcast' => 'contacts#webcast'

  get '/assets' => 'assets#index'
  #This route is for file downloads 
  match "assets/get/:id" => "assets#get", :via => [:get], :as => "download"
  #To browse across folders
  match "browse/:folder_id" => "assets#browse",  :via => [:get], :as => "browse"
 
  #creating folders insiide another folder 
  match "browse/:folder_id/new_folder" => "folders#new", :via => [:get], :as => "new_sub_folder"

  #for uploading files to folders 
  match "browse/:folder_id/new_file" => "assets#new", :via => [:get], :as => "new_sub_file"
  #for renaming a folder 
  match "browse/:folder_id/rename" => "folders#edit", :via => [:get], :as => "rename_folder"

  #for sharing the folder 
  match "assets/share" => "assets#share", :via => [:post], :as => "share"

  resources :appointments, except: [:create, :edit, :show, :update, :destroy, :new]
  post '/appointments/make_payment/:id' => "appointments#make_payment", as: :make_payment

  # Resourceful routes for the contacts page
  resources :contacts , except: [:show, :destroy]do
    member do
      get :delete
    end  
  end  
  resources :conversations do
    resources :messages
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/contacts_controller.rb
require "#{Rails.root}/app/controllers/push_notifications"

class ContactsController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_customer, only: [:create_appointment]
  skip_before_action :verify_authenticity_token
  require "opentok"

  def index
  	@contacts = current_user.contacts
  	@contacts_physicians = current_user.contacts.where(role: 'doctor')
    @contacts_patients = current_user.contacts.where(role: 'patient')
  	me = Array.new
  	me << current_user
  	# Remove current user and pass the remaining users
  	
    @users_physicians = User.where(role: 'doctor') - me - @contacts
    @users_patients = User.where(role: 'patient') - me - @contacts

    @all_users = []
  respond_to do |format|
    format.html
    format.json { render json: @contacts }
  end
    

  end

  def show
	redirect_to(:action => "index")
  end

  def delete
   	# Delete and Destroy a contact
    user = User.find(params[:id])

    current_user.remove_contact(user)
    user.remove_contact(current_user)
    flash[:alert] = "#{user.first_name} #{user.last_name} has been removed from your contacts" 
  	redirect_to(:action => "index", :frag => "2a")	
  end

  def destroy
  	redirect_to(:action => "index")
  end	

  # Being reused for add - to be changed later
  def edit
 	  user = User.find(params[:id])
 	  current_user.add_contact(user)
    user.add_contact(current_user)
    flash[:notice] = "Your contacts have been updated" 	
 	  redirect_to(:action => "index")
  end	

  def create_session
    # Create a new session if dialed via the contact page
    opentok = OpenTok::OpenTok.new(API_OPENTOK[:key], API_OPENTOK[:secret])
    # Create a session id
    session_id = opentok.create_session.session_id
    # Update session id to the current user database
    current_user.session_id = session_id
    current_user.save
    contact = User.find(params[:id])
    # Update session id to the contacts database
    contact.session_id = session_id
    contact.save
    
    notification = PushNotification.new("Incoming call", "#{current_user.first_name} #{current_user.last_name} is calling you", webcast_url, contact.id)
    notification.push()

    redirect_to(:action => "webcast")
  end  

  def mail_session

    @recp=User.find(params[:id])
    redirect_to conv_session_path(:recp => @recp)
  end

  def webcast
    
    opentok = OpenTok::OpenTok.new(API_OPENTOK[:key], API_OPENTOK[:secret])
    @session_id = current_user.session_id
    if (@session_id.empty?)
      redirect_to(:action => "index")   
    else
      @token = opentok.generate_token(@session_id)
    end  
    
  end  

  def create_appointment
    @appointment = Appointment.new
    @receiver = User.find(params[:id])
    respond_to do |format|

      if @appointment.create_appointment(params, current_user)
        if !@appointment.new_record?
          notification = PushNotification.new("Appointment", "Dr. #{current_user.first_name} #{current_user.last_name} has scheduled an appointment with you", appointments_url, @receiver.id)
          notification.push()

          UserMailer.new_appointment(current_user,@receiver).deliver
          flash[:notice] = "Appointment scheduled with #{@receiver.first_name} #{@receiver.last_name} for #{params[:appointment][:datetime]}"
          redirect_to(:action => "index")  
        end  
        
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @appointment.errors.full_messages,
                                   status: :unprocessable_entity }
      end
    end
  end  

  def get_customer
    user = User.find(params[:id])
    @contacts = user.contacts
    respond_to do |format|
      format.html
      format.json { render json: @contacts }
    end
  
  end

  def set_customer
    puts "================================"
    puts "================================"
  
    user = User.find(params[:id])
    @contacts = user.contacts
    respond_to do |format|
      format.html
      format.json { render json: @contacts }
    end

  end

private 
  


  
  def contact_params
    params.require(:contact).permit(:first_name, :last_name)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_all_contacts_patients.html.erb
<br>
<br>
<table class="dtable display responsive nowrap" cellspacing="0" width="100%">
<!-- 	<col width="30%">
	<col width="20%">
	<col width="20%">
	<col width="10%">
	<col width="10%">
	<col width="10%"> -->	
<thead>	
	<!-- Header -->
	<tr class = "header">
		<th> Name </th>
		<th> Location </th>
		<th> Date of Birth </th>
<!-- 		<th> Message </th>
		<th> Call </th> -->
		<th> Delete </th>
		<th> Appointment </th>
	</tr>
</thead>
	<!-- Body -->
	<tbody>
		<% @contacts_patients.each do |contact| %>
		<tr>
			<!-- Name -->
			<td><%= "#{contact.first_name} #{contact.last_name}" %></td>
			<td><%= "#{contact.location}" %></td>
			<td><%= "#{contact.d_o_b.strftime('%m-%d-%Y')}" %></td>
			<!-- Buttons -->
<!-- 			<td>
				<%=  link_to mail_session_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-envelope "></span><span style="font-size: 0;">message</span>
				<% end %>
			</td>
			<td>
				<%= link_to create_session_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-facetime-video"></span><span style="font-size: 0;">call</span>
				<% end %>
			</td> -->
			<td>	
				<%= link_to delete_contact_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-trash "></span><span style="font-size: 0;">delete</span>
				<% end %>
			</td>

			<td>	
				<%= link_to  create_appointment_path(contact),:method => "post", remote: true, :class => 'btn btn-primary' do%>
				<span class="glyphicon glyphicon-calendar "><span style="font-size: 0;">appointment</span></span>

				<% end %>
    
			</td>

		</tr>
		<%end%>
	</tbody>	
</table>
&nbsp;&nbsp;&nbsp;

app/views/contacts/_all_contacts_physicians.html.erb
<br>
<br>
<table class="dtable display responsive nowrap" cellspacing="0" width="100%">
<!-- 	<col width="30%">
	<col width="20%">
	<col width="20%">
	<col width="10%">
	<col width="10%">
	<col width="10%">	 -->
<thead>	
	<!-- Header -->
	<tr class = "header">
		<th> Name </th>
		<th> Location </th>
		<th> Area of Interest </th>
<!-- 		<th> Message </th>
		<% if current_user.role != "patient" %>
			<th> Call </th>
		<% end %> -->	
		
		<th> Delete </th>

		<% if current_user.role != "patient" %>
			<th> Appointment </th>
		<% end %>
			
	</tr>
</thead>
	<!-- Body -->
	<tbody>
		<% @contacts_physicians.each do |contact| %>
		<tr>
			<!-- Name -->
			<td><%= "#{contact.first_name} #{contact.last_name}" %></td>
			<td><%= "#{contact.location}" %></td>
			<td><%= "#{contact.specialization}" %></td>
			<!-- Buttons -->
<!-- 			<td>
				<%=  link_to mail_session_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-envelope "></span>
				<% end %>
			</td>

			<% if current_user.role != "patient" %>
			<td>
				<%= link_to create_session_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-facetime-video"></span>
				<% end %>
			</td>
			<% end %> -->


			<td>	
				<%= link_to delete_contact_path(contact), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-trash "></span>
				<% end %>
			</td>

			<% if current_user.role != "patient" %>	
			<td>	
				<%= link_to  create_appointment_path(contact),:method => "post", remote: true, :class => 'btn btn-primary' do%>
				<span class="glyphicon glyphicon-calendar "></span>

				<% end %>
    
			</td>
			<% end %>
		</tr>
		<%end%>
	</tbody>	
</table>

app/views/contacts/_all_users_patients.html.erb
<br>
<br>
<table class="dtable display responsive" cellspacing="0" width="100%">
<!-- 	<col width="30%">
	<col width="30%">
	<col width="30%">
	<col width="10%"> -->	
<thead>	
	<!-- Header -->
	<tr class = "header">
		<th> Name </th>
		<th> Location </th>
		<th> Date of Birth </th>
		<th> Add Contact</th>
	</tr>
</thead>
	<!-- Body -->
	<tbody>
		<% @users_patients.each do |contact| %>
		<tr>
			<!-- Name -->
			<td><%= "#{contact.first_name} #{contact.last_name}" %></td>
			<td><%= "#{contact.location}" %></td>
			<td><%= "#{contact.d_o_b.strftime('%m-%d-%Y')}" %></td>
			<!-- Buttons -->
			<td class = "actions">
				<%= link_to edit_contact_path(contact.id), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-plus "></span>
				<% end %>
			</td>	
		</tr>
		<%end%>
	</tbody>	
</table>

app/views/contacts/_all_users_physicians.html.erb
<br>
<br>
<table class="dtable display responsive nowrap" cellspacing="0" width="100%">
<!-- 	<col width="30%">
	<col width="30%">
	<col width="30%">
	<col width="10%">	 -->
<thead>	
	<!-- Header -->
	<tr class = "header">
		<th> Name </th>
		<th> Location </th>
		<th> Area of Interest</th>
		<th> Add Contact</th>
	</tr>
</thead>
	<!-- Body -->
	<tbody>
		<% @users_physicians.each do |contact| %>
		<tr>
			<!-- Name -->
			<td><%= "#{contact.first_name} #{contact.last_name}" %></td>
			<td><%= "#{contact.location}" %></td>
			<td><%= "#{contact.specialization}" %></td>
			<!-- Buttons -->
			<td class = "actions">
				<%= link_to edit_contact_path(contact.id), class: "btn btn-primary " do %>
    				<span class="glyphicon glyphicon-plus "></span>
				<% end %>
			</td>	
		</tr>
		<%end%>
	</tbody>	
</table>

app/views/contacts/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="false" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/contacts/_form.html.erb
<%= form_for(@appointment, remote: true, :html => { :role => "form" }, url: "/contacts/create_appointment/#{params[:id]}")do |f| %>

	<%= "Schedule and appointment with #{@receiver.first_name} #{@receiver.last_name}"%> 
	<br>
	<br>
	<div class='input-group date' id='datetimepicker1'>
    	<%= f.text_field :datetime, class: 'form-control', placeholder: 'Date and Time' %>
        	<span class="input-group-addon">
            	<span class="glyphicon glyphicon-calendar"></span>
        	</span>
  	</div>

  	<br>
	<div class="field input-group">
		
    	<%= f.text_field :price, class: 'form-control currency', placeholder: 'Price' %>
    	<span class="input-group-addon" id = "dollar">$</span>
	</div>

	 <div class="form-group">
	 	<br>
    	<%= f.submit  :class => "btn btn-primary" %>
  	</div>



<% end %>

app/views/contacts/create_appointment.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-calendar custom-blue'></i> <span class ='custom-blue'>Appointment</span>");
 
// Render the edit form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

$('#datetimepicker1').datetimepicker({
	format: 'DD-MM-YYYY HH:mm'
});

app/views/contacts/index.html.erb
<div class="container contacts-container">
<div class="container"><h1> </h1></div>
<div id="exTab1">	
	<ul  class="nav nav-pills nav-justified panel">
			<li id = "b1a" class="active">
        	<a  href="#1a" data-toggle="tab"><b>Instructors</b></a>
			</li>

			<% if current_user.role != "patient" %>
				<li id = "b2a"><a href="#2a" data-toggle="tab"><b>Students</b></a>
				</li>
			<% end %>

			<li id = "b3a"><a href="#3a" data-toggle="tab"><b>All Instructors</b></a>
			</li>
  			
  			<% if current_user.role != "patient" %>
  				<li id = "b4a"><a href="#4a" data-toggle="tab"><b>All Students</b></a>
				</li>
			<% end %>
				
	</ul>

			<div class="tab-content clearfix">
			  <div class="tab-pane active" id="1a">
          			<%= render '/contacts/all_contacts_physicians' %>
				</div>
				<div class="tab-pane " id="2a">
          			<%= render '/contacts/all_contacts_patients' %>
				</div>
        		<div class="tab-pane " id="3a">
          			<%= render '/contacts/all_users_physicians' %>
				</div>
          		<div class="tab-pane " id="4a">
          			<%= render '/contacts/all_users_patients' %>
				</div>
			</div>
			<%= render 'dialog' %>
</div>
</span>
<script>

$(document).ready(function() {
	
	frag = window.location.search.split('frag=')[1]
	if (!frag == false) {
		$('#1a').removeClass('active');
  		$('#2a').removeClass('active');
  		$('#3a').removeClass('active');
  		$('#4a').removeClass('active');


  		$('#b1a').removeClass('active');
  		$('#b2a').removeClass('active');
  		$('#b3a').removeClass('active');
  		$('#b4a').removeClass('active');

  		$('#'+frag).addClass('active');
  		$('#b'+frag).addClass('active');

	}	

 


	$('.dtable').DataTable({
  	responsive: true,
  autoWidth: true
});

   $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
         .columns.adjust()
         .responsive.recalc();
   }); 	
});


</script>

app/views/contacts/index_bak.html.erb
<div class="row">

<!-- List all users to be added	 -->
<div class="col-sm-6 col-xs-12 ">
	<% if current_user.role != "patient" %>	
		<div class= "panel">
			<%= render '/contacts/all_contacts_doctor' %>
			<br>
		</div>
	<% else %>
		<div class= "panel">
			<%= render '/contacts/all_contacts_patient' %>
			<br>
		</div>	
		<small style="color:grey;"> Please request your Physicians to add you to their contacts </small>
	<% end %>	
</div>

<!-- List existing contacts -->
<div class="col-sm-6 col-xs-12 panel">
	<% if current_user.role != "patient" %>	
	<%= render '/contacts/all_users' %>
	<% end %>
	<br>
</div>

</div>	

<!-- Responsive Datatable -->
<script>
$(document).ready(function() {
	$('.dtable').dataTable({
  responsive: true
});
});
</script>

app/views/contacts/webcast.html.erb
<script type="text/javascript">
        var apiKey = '<%= API_OPENTOK[:key] %>';
        var sessionId = '<%= @session_id %>';
        var token = '<%= @token %>';
</script>

<script src="/js/webcast.js"></script>
    <br>
    <div id="subscribers" style="height: 100vh; width: 100%;" ></div>
    <br>
    <div id="publisher"></div>
    <div class="web-buttons row">
        <div class="col-md-4 col-xs-2"></div>    
        <div class="col-md-2 col-xs-3"><button id="mute_audio" type="button" class="btn btn-circle btn-lg white-button"><span class="glyphicon glyphicon-volume-up"></span></button></div>
        <div class="col-md-2 col-xs-3"><button id="end_call" type="button" class="btn btn-danger btn-circle btn-lg "><span class="glyphicon glyphicon-earphone"></span></button></div>
        <div class="col-md-2 col-xs-3"><button id="stop_video" type="button" class="btn btn-circle btn-lg white-button"><span class="glyphicon glyphicon-eye-open"></span></button></div>
    </div>
    <script>
    $("#end_call").click(function() {
        session.disconnect();
        // <% flash[:notice] = "Your call has been disconnected"  %>
        window.location.href="/launchpad"
    });


    $("#mute_audio").click(function() {

        $("span", this).toggleClass("glyphicon-volume-off glyphicon-volume-up");
        if($( "#mute_audio span" ).hasClass( "glyphicon-volume-up" )) {
            publisher.publishAudio(true)
        }
        else {
            publisher.publishAudio(false)   
        }
    });

    $("#stop_video").click(function() {

        $("span", this).toggleClass("glyphicon-eye-close glyphicon-eye-open");
        if($( "#stop_video span" ).hasClass( "glyphicon-eye-open" )) {
            publisher.publishVideo(true)
        }
        else {
            publisher.publishVideo(false)   
        }
    });




 </script>