config/routes.rb
Rails.application.routes.draw do

  resources :courses
  resources :folders
  resources :assets

  devise_for :users
  # Define root URI
  devise_scope :user do
  	authenticated :user do
      #Naming the root routes causes mailboxer to crash when email is sent. Do not uncomment till fixed
    	root :to => 'pages#launchpad'#, as: :authenticated_root
  	end
  	unauthenticated :user do

    	root :to => 'devise/registrations#new'#, as: :unauthenticated_root
  	end
  end
  
  get '/courses/watch/:id' => 'courses#watch', as: :watch

  get '/courses/attend/:id'	=> "courses#attend", as: :attend
  # get "/courses/start_teaching/:id" => "courses#start_teaching", as: :start_teaching
  # get "/courses/start_learning/:id" => "courses#start_learning", as: :start_learning
  get "/courses/webcast/:id" => "courses#webcast", as: :start_teaching

  # Match routes for static pages
  get '/launchpad' => 'pages#launchpad'
  get '/add_push_session' => 'pages#add_push_session'
  get "/contacts/create_session/:id" => "contacts#create_session", as: :create_session
  post "/contacts/create_appointment/:id" => "contacts#create_appointment", as: :create_appointment


  post "/contacts/set_customer/:id" => "contacts#set_customer"
  get "/contacts/get_customer/:id" => "contacts#get_customer"
  
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  get "/contacts/mail_session/:id" => "contacts#mail_session", as: :mail_session
  get "/conversations/new_wrecp" => "conversations/new_wrecp", as: :conv_session
  post "/conversations/invite" => "conversations#invite", as: :invite
  #Route for webcast
  get '/webcast' => 'contacts#webcast'

  get '/assets' => 'assets#index'
  #This route is for file downloads 
  match "assets/get/:id" => "assets#get", :via => [:get], :as => "download"
  #To browse across folders
  match "browse/:folder_id" => "assets#browse",  :via => [:get], :as => "browse"
 
  #creating folders insiide another folder 
  match "browse/:folder_id/new_folder" => "folders#new", :via => [:get], :as => "new_sub_folder"

  #for uploading files to folders 
  match "browse/:folder_id/new_file" => "assets#new", :via => [:get], :as => "new_sub_file"
  #for renaming a folder 
  match "browse/:folder_id/rename" => "folders#edit", :via => [:get], :as => "rename_folder"

  #for sharing the folder 
  match "assets/share" => "assets#share", :via => [:post], :as => "share"

  resources :appointments, except: [:create, :edit, :show, :update, :destroy, :new]
  post '/appointments/make_payment/:id' => "appointments#make_payment", as: :make_payment

  # Resourceful routes for the contacts page
  resources :contacts , except: [:show, :destroy]do
    member do
      get :delete
    end  
  end  
  resources :conversations do
    resources :messages
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/asset.rb
class Asset < ApplicationRecord
	belongs_to :user
  # belongs_to :folder

#set up "uploaded_file" field as attached_file (using Paperclip) 
  
  has_attached_file :uploaded_file, #styles: { medium: "300x300>", thumb: "100x100#" },

                    :url => "/assets/get/:id", 
                    :path => ":Rails_root/assets/:id/:basename.:extension"

  #validates_attachment_presence :uploaded_file
  #validates :uploaded_file, attachment_presence: true

  #Only presence validation not working, have to give a file type, why?

  # validates_attachment_content_type :uploaded_file, content_type: [/\Aimage\/.*\z/, "application/pdf","application/vnd.ms-excel",     
  #            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  #            "application/msword", 
  #            "application/vnd.openxmlformats-officedocument.wordprocessingml.document", 
  #            "text/plain"]

  validates_attachment_content_type :uploaded_file, content_type:[]

  def file_name 
    uploaded_file_file_name 
  end

  def file_size 
    uploaded_file_file_size 
  end

  def folder
    if self.folder_id
    return Folder.find(self.folder_id)
    end
  end  
end

app/controllers/assets_controller.rb
require "#{Rails.root}/app/controllers/push_notifications"

class AssetsController < ApplicationController
  before_action :authenticate_user!  #authenticate for users before any methods is called
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
 


def index 
    if user_signed_in? 
      #show folders shared by others 
      @being_shared_folders = current_user.shared_folders_by_others 
    
      #show only root folders 
      @folders = current_user.folders.roots 
      #show only root files 
      @assets = current_user.assets.where("folder_id is NULL").order("uploaded_file_file_name desc")       
    end
end
  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  # def new
  #   @asset = current_user.assets.new
  # end

  def new
  @asset = current_user.assets.new     
  if params[:folder_id] #if we want to upload a file inside another folder 
   @current_folder = current_user.folders.find(params[:folder_id]) 
   @asset.folder_id = @current_folder.id 

  end
end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  #  def create
  #    @asset = current_user.assets.new(asset_params)

  #    respond_to do |format|
  #      if @asset.save
  #        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
  #        format.json { render :show, status: :created, location: @asset }
  #      else
  #        format.html { render :new }
  #        format.json { render json: @asset.errors, status: :unprocessable_entity }
  #      end
  #    end
  # end


 def create 
   puts asset_params.inspect

   @asset = current_user.assets.new(asset_params)

   if @asset.save 
    flash[:notice] = "Successfully uploaded the file."
  
    if @asset.folder #checking if we have a parent folder for this file 
      # redirect_to '/assets'
      redirect_to browse_path(@asset.folder)  #then we redirect to the parent folder 
    else
      redirect_to '/assets' 
    end      
   else
    puts "+-=-=-"
    
    puts @asset.inspect
    render 'new'
   end
 end




  # # PATCH/PUT /assets/1
  # # PATCH/PUT /assets/1.json
  # def update
  #   respond_to do |format|
  #     if @asset.update(asset_params)
  #       format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @asset }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @asset.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /assets/1
  # DELETE /assets/1.json
  # def destroy
  #   @asset.destroy
  #   respond_to do |format|
  #     format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end


def destroy 
  @asset = current_user.assets.find(params[:id]) 
  @parent_folder = @asset.folder #grabbing the parent folder before deleting the record 
  @asset.destroy 
  flash[:notice] = "Successfully deleted the file."
  
  #redirect to a relevant path depending on the parent folder 
  if @parent_folder
   redirect_to browse_path(@parent_folder) 
  else
   redirect_to '/assets' 
  end
end




  #This action will let the users download the files (after a simple authorization check) 
  # def get 
  #   asset = current_user.assets.find_by_id(params[:id]) 
  #     if asset 
  #        send_file asset.uploaded_file.path, :type => asset.uploaded_file_content_type 
  #     else
  #       flash[:error] = "Don't be cheeky! Mind your own assets!"
  #       redirect_to assets_path
  #     end
  # end


  def get 
 #first find the asset within own assets 
 asset = current_user.assets.find_by_id(params[:id]) 
  
 #if not found in own assets, check if the current_user has share access to the parent folder of the File 
 asset ||= Asset.find(params[:id]) if current_user.has_share_access?(Asset.find_by_id(params[:id]).folder) 
  
 if asset 
   #Parse the URL for special characters first before downloading 
   # data = open(URI.parse(URI.encode(asset.uploaded_file.url))
   send_file asset.uploaded_file.path, :type => asset.uploaded_file_content_type  
   # send_data data, :filename => asset.uploaded_file_file_name 
   #redirect_to asset.uploaded_file.url 
 else
   flash[:error] = "Don't be cheeky! Mind your own assets!"
     redirect_to assets_path 
 end
end

  #this action is for viewing folders 
# def browse 
#     #get the folders owned/created by the current_user 
#     @current_folder = current_user.folders.find(params[:folder_id])   
  
#     if @current_folder
#        #if under a sub folder, we shouldn't see shared folders 
#       @being_shared_folders = []
    
#       #getting the folders which are inside this @current_folder 
#       @folders = @current_folder.children 
  
#       #We need to fix this to show files under a specific folder if we are viewing that folder 
#      # @assets = current_user.assets.order("uploaded_file_file_name desc") 
#        #show only files under this current folder 
#       @assets = @current_folder.assets.order("uploaded_file_file_name desc")
  
#       render "index"
#     else
#       flash[:error] = "Don't be cheeky! Mind your own folders!"
#       redirect_to '/assets' 
#     end
# end



def browse 
  #first find the current folder within own folders 
  @current_folder = current_user.folders.find_by_id(params[:folder_id])   
  @is_this_folder_being_shared = false if @current_folder #just an instance variable to help hiding buttons on View 
    
  #if not found in own folders, find it in being_shared_folders 
  if @current_folder.nil? 
    folder = Folder.find_by_id(params[:folder_id]) 
      
    @current_folder ||= folder if current_user.has_share_access?(folder) 
    @is_this_folder_being_shared = true if @current_folder #just an instance variable to help hiding buttons on View 
      
  end
    
  if @current_folder
       #if under a sub folder, we shouldn't see shared folders 
      @being_shared_folders = []
    
      #getting the folders which are inside this @current_folder 
      @folders = @current_folder.children 
  
      #We need to fix this to show files under a specific folder if we are viewing that folder 
     # @assets = current_user.assets.order("uploaded_file_file_name desc") 
       #show only files under this current folder 
      @assets = @current_folder.assets.order("uploaded_file_file_name desc")
  
      render "index"
    else
      flash[:error] = "Don't be cheeky! Mind your own folders!"
      redirect_to '/assets' 
    end
end







 


#this handles ajax request for inviting others to share folders 
def share     

    people = params[:people]  
      
    people.each do |user_id| 
      #getting the shared user id right the owner the email has already signed up with ShareBox 
      #if not, the field "shared_user_id" will be left nil for now. 
      shared_user = User.find(user_id.to_i)

      #save the details in the ShareFolder table 
      @shared_folder = current_user.shared_folders.new
      @shared_folder.folder_id = params[:folder_id] 
      @shared_folder.shared_email = shared_user.email

       
    
       
      @shared_folder.shared_user_id = shared_user.id if shared_user 
    
      @shared_folder.message = params[:message] 
      @shared_folder.save 
    

      notification = PushNotification.new("Shared Document", "#{current_user.first_name} #{current_user.last_name} has shared documents with you", assets_url, shared_user.id)
      notification.push()
     #now we need to send email to the Shared User 
    end
  
    #since this action is mainly for ajax (javascript request), we'll respond with js file back (refer to share.js.erb) 
    respond_to do |format| 
      format.js { 
      } 
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = current_user.assets.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:user_id, :uploaded_file, :folder_id, :parent_id,  :shared_email, :shared_user_id,  :message)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_breadcrumbs.html.erb
<!-- <div class="breadcrumbs">          -->
    <% if @current_folder #checking if we are under any folder %> 
        
        <%=  link_to '/assets' do %>
        <i class="fa fa-home fa-3x" aria-hidden="true"></i>
        <%end%> 
        <% @current_folder.ancestors.reverse.each do |folder| %> 
            » <%= link_to folder.name, browse_path(folder) %> 
        <% end %> 
         »  <%= @current_folder.name %> 
    <% else #if we are not under any folder%> 
        <i class="fa fa-home fa-3x" aria-hidden="true" style="color: #6fadf3;"></i>
    <% end %> 
<!-- </div> -->

app/views/assets/_form.html.erb
<%= form_for @asset, :html => {:multipart => true} do |f| %> 
 <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
  
   <p> 
    <br>
    <br>
  <div class="row">
    <div class="col-md-9 col-xs-9">
        <div class="input-group">
      <label class="input-group-btn">
        <span class="btn btn-primary btn-file">
        <!--Add attachment <%= f.file_field :uploaded_file, style: "display: none;"%> -->
        Add attachment <%= f.file_field :uploaded_file%> 
        </span>
      </label>
      <input type="text" id="attachment-text" class="form-control" readonly="">
    </div>
  </div>
       <!-- <%= f.label :uploaded_file, "File" %><br /> -->
       <!-- <%= f.file_field :uploaded_file , class: 'form-control'%> -->
     
     <div class="col-md-3 col-xs-3">
       <%= f.hidden_field :folder_id %> 
 <%= f.submit "Upload", class:'btn btn-large btn-primary ' %></p> 
</div>
</div>
<% end %>
    

<script>
$(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
    console.log(numFiles);
    console.log(label);
    document.getElementById("attachment-text").value = label;
});
</script>    

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<!-- <%= stylesheet_link_tag "assets"%> -->
<!-- <h1>Assets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.user_id %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>
 -->
<!-- <h1>Assets</h1> 
<table> 
  <tr> 
    <th>Uploaded Files</th> 
  </tr> 
  <% for asset in @assets %> 
    <tr> 
      <td><%= link_to asset.file_name, download_url(asset) %></td> 
      <td><%= link_to "Show", asset %></td> 
      <td><%= link_to "Edit", edit_asset_path(asset) %></td> 
      <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
    </tr> 
  <% end %> 
</table> 
<p><%= link_to "New Asset", new_asset_path %></p> -->
</br>

<!-- </ul> -->

    <!-- </div> -->
<% unless @is_this_folder_being_shared %> 
    <div class="row">
      <div class="col-md-9 col-xs-12">
    <%= render :partial => "breadcrumbs" %>
    </div>
      <% if @current_folder %> 
      <div class="col-md-1 col-xs-12">
       <%= link_to "Upload", new_sub_file_path(@current_folder), class: "btn btn-primary " %>
       <br>
       </div>
       <div class="col-md-1 col-xs-12">
       <%= link_to "New Folder", new_sub_folder_path(@current_folder), class: "btn btn-primary " %> 
       </div>
   <% else %> 
       <div class="col-md-1 col-xs-3">
       <%= link_to "Upload", new_asset_path, class: "btn btn-primary " %>
       <br>
     </div>
     <div class="col-md-1 col-xs-9">
       <%= link_to "New Folder", new_folder_path, class: "btn btn-primary " %> 
     </div>
   <% end %> 
    </br>
    <br>
  </div>
  <br>
 <% else %> 
    <h3>This folder is being shared to you by a user</h3> 
<% end %>

<div class="table-responsive">
  <table class="table">  
    <tr>
      <th>Name</th> 
      
      <th>Size</th>
      
      <th>Modified</th> 
      <th></th>
      <th></th> 
      <th></th> 
    </tr>
 

 
<!-- Listing Shared Folders (the folders shared by others) -->
<% @being_shared_folders.each do |folder| %> 
  <tr>
  <td> <i class="fa fa-folder " aria-hidden="true" style="color: #6fadf3;"></i> <%= link_to folder.name, browse_path(folder) , style: "color: black;"%> </td>

  <td>-</td>
  

  <td>-</td>

  <td> </td>
  <td> </td>
  <td> </td>
</tr>
     
<% end %> 




  
    <!-- Listing Folders -->
<% @folders.each do |folder| %> 
  <tr>
    <td> <i class="fa fa-folder " aria-hidden="true" style="color: #6fadf3;"></i> <%= link_to folder.name, browse_path(folder) , style: "color: black;"%> </td>
  
    <td>-</td>
  

    <td>-</td> 
  
    <td>
      <div class="share">
        <%= link_to "Share", "#", :folder_id => folder.id, :folder_name => folder.name unless @is_this_folder_being_shared %> 
      </div>
    </td> 
                
    <td><%= link_to "Rename", rename_folder_path(folder) unless @is_this_folder_being_shared %></td> 
                 
    <td><%= link_to "Delete", folder, method: :delete  unless @is_this_folder_being_shared %></td>
  </tr>

<% end %>



  
   <!-- Listing Files -->
    <% @assets.each do |asset| %> 
    <tr>
      <td> <i class="fa fa-file" aria-hidden="true" style="color: #6fadf3;"></i> <%= link_to asset.file_name, download_url(asset), style: "color: black;" %></td> 
  
      <td><%= number_to_human_size(asset.file_size, :precision => 2) %></td> 
  
      <td><%= asset.uploaded_file_updated_at %></td> 
               
      <td><%= link_to "Download", download_url(asset) %></td>

      <td><%= link_to "Delete", asset, method: :delete %></td>
      <td></td>
    </tr>
         
  <% end %>
  </table>
</div>

<div id="invitation_form" title="Invite others to share" style="display:none">

    <%= form_tag '/assets/share' do  %>  

    <% users = [] %>
    <% current_user.contacts.each do |uu|%>
        <% u = User.new %>
        <% u.id = uu.id %>
        <% u.first_name = "#{uu.first_name} #{uu.last_name}" %>
        <% users << u %>
    <% end %>
    <%= select_tag "people", options_from_collection_for_select(users,"id",:first_name ), multiple: true, class: 'form-control js-example-basic-multiple',id: "recipients", placeholder: "Share with ..."%>


    
    <br>

            <%= hidden_field_tag "folder_id" %>
    <% end %>  

    <script type="text/javascript">
var $exampleMulti = $(".js-example-basic-multiple").select2({tags: true});
$exampleMulti.select2('val', [<%= (params[:recp])? params[:recp]:"" %>]);
$(".js-example-basic-multiple").on('select2:select', function (e) { 
    //var selected_element = $(e.currentTarget);
    //var select_val = selected_element.val().pop();
    //console.log(parseInt(select_val),selected_element.val())

  new_val=$.grep($(".js-example-basic-multiple").select2('val'), function (value) {
    if (!(isNaN(parseInt(value)))){
      return true;
    }
    
  });
  
  //$(".js-example-basic-multiple").select2('data', new_data);
  $exampleMulti.val(new_val).trigger("change")

    //if(isNaN(parseInt(select_val))){
     //   $('#invite_form').modal("show");
      //  $(".js-example-basic-multiple").select2('val',selected_element.val());
      //}

});
</script>



</div>

<script>
$( document ).ready(function () {  
    //open the invitation form when a share button is clicked 
    $( ".share a" ) 
            .click(function() { 
                //assign this specific Share link element into a variable called "a" 
                var a = this; 
                  
                //First, set the title of the Dialog box to display the folder name 
                $("#invitation_form").attr("title", "Share '" + $(a).attr("folder_name") + "' with others" ); 
                  
                //a hack to display the different folder names correctly 
                $("#ui-dialog-title-invitation_form").text("Share '" + $(a).attr("folder_name") + "' with others");  
                  
                //then put the folder_id of the Share link into the hidden field "folder_id" of the invite form 
                $("#folder_id").val($(a).attr("folder_id")); 
                  
                //Add the dialog box loading here
                //the dialog box customization 
$( "#invitation_form" ).dialog({ 
    height: 160, 
    width: 400, 
    modal: true, 
    buttons: { 
        //First button 
        "Share": function() { 
            //get the url to post the form data to 
            var post_url = $("#invitation_form form").attr("action"); 
              
            //serialize the form data and post it the url with ajax 
            $.post(post_url,$("#invitation_form form").serialize(), null, "script"); 
              
            return false; 
        }, 
        //Second button 
        Cancel: function() { 
            $( this ).dialog( "close" ); 
        } 
    }, 
    close: function() { 
  
    } 
}); 
                  
                return false; 
            }); 
});

  

</script>

app/views/assets/new.html.erb
<h1>Upload a file</h1></br>
 
<%= render :partial => "assets/breadcrumbs" %> 
  
<%= render 'form' %> 
  
<p> 
<% if @asset.folder %> 
   <%= link_to "Back to '#{@asset.folder.name}' Folder", browse_path(@asset.folder) %> 
<% else %> 
   <%= link_to "Back", '/assets' %> 
<% end %> 
</p>

app/views/assets/share.js.erb
//closing the dialog box 
$("#invitation_form").dialog("close"); 
  
//making sure we don't display the flash notice more than once 
$("#flash_notice").remove(); 
  
//showing a flash message 
$("#container").prepend("<div id='flash_notice'>Successfully shared the folder</div>");

// //Removing the css class 'folder' 
// $("#folder_<%= params[:folder_id] %>").removeClass("folder"); 
  
// //Adding the css class 'shared_folder' 
// $("#folder_<%= params[:folder_id] %>").addClass("shared_folder");

msg = "<br><br><div class=\"alert alert-notice\"><a href=\"#\" data-dismiss=\"alert\" class=\"close\">×</a><ul id=\"test\"><li>Folder successfully shared</li></ul></div>";
document.getElementById('cont').innerHTML = msg + document.getElementById('cont').innerHTML;

$(document).ready(function(){
  setTimeout(function(){
    $('.alert').fadeOut();
  }, 2000);
 })

app/views/assets/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= image_tag @asset.uploaded_file.url(:thumb) %>

<p>
  <strong>User:</strong>
  <%= @asset.user_id %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>